---
- name: Avvio dei container senza conflitto di porte (Podman)
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}:latest"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ item.host_port }}:{{ item.container_port }}"
  loop: "{{ run_containers_list }}"
  loop_control:
    label: "{{ item.name }} ({{ item.host_port }}->{{ item.container_port }})"